### ISSUE TITLE
map - button

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-editor#18]
In the top menu-bar a "Map" button would be great, if people enter the editor straight away, or want to open the map they closed before.

**Comment by josefkreitmayer** [comment]
@species

**Comment by josefkreitmayer** [comment]
@species 

---

I just noticed, that the link is to the non-editable map. I think it should be to the editable map, if the user wants to edit several initiatives at once, or see if some is already there.

- For Transformap editor: 
http://viewer.transformap.co/editable.html

- for SUSY-Editor:
https://susy-partners.github.io/transformap-viewer/editable.html

---

- push of the Button-Link to SUSY-Map is still open.

---

Is there any possibility, the map could open at the same zoom level and location, as the POI-window of the editor? That would be awsome. The location is currently displayed in the slug of the editor. right?
thx : )

**Comment by josefkreitmayer** [comment]
Is there any possibility, the map could open at the same location, as the POI-Window of the editor?

**Comment by species** [comment]
I will push all changes i make today to the susy map at once - that saves time.

**Comment by species** [comment]
Links to correct map location implemented.
All changes deployed on all forks. gn8.

**Comment by josefkreitmayer** [comment]
geil!
