### ISSUE TITLE
Address-Geocoder automated zoom to address

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-editor#2]
When the address is entered, the bounding box should move to the location and set the marker on the address.

**Comment by josefkreitmayer** [comment]
@species I would prioritize this over the other possible developments with the editor.

**Comment by species** [comment]
fixed in 6fbbc65bd5ee8efbccb83c2b1715156b4ffdd77f.
Please test:
http://transformap.co/transformap-editor/?place=e98fb9126657fd09e8c7e4321701fe05#18/47.06508/15.45219

**Comment by josefkreitmayer** [comment]
Works great!
Also the popup, when the address is without house number, or just the city, is great!

-----

When there is no house-number set, and the popup appears, there is no marker set on the map.

**Comment by species** [comment]
That there is no marker set is intended - how should we know where to place a marker when we don't have the exact position?
The popup reads: "...please place the marker manually!"

**Comment by josefkreitmayer** [comment]
How can the manual positioning of the marker be done as a user? I tried it,
but could not achieve.

2017-01-16 11:08 GMT+01:00 Michael Maier <notifications@github.com>:

**Comment by josefkreitmayer** [comment]
done!

open issues: 
- https://github.com/TransforMap/transformap-editor/issues/14 - further field in the address-search
- https://github.com/TransforMap/transformap-editor/issues/13 - delete marker, when new OSM-coordinate query is requested
