### ISSUE TITLE
load newest version of wikibase RDF-export

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-editor#24]
The newest version of the RDF-Export is needed

- the "other categories" are renewed with labels, that state each category to which the "other belongs"
- food buying circle was not understood and is replaced by food buying collective

**Comment by josefkreitmayer** [comment]
@species
possibly @almereyda

**Comment by species** [comment]
with help of @almereyda, done.

**Comment by josefkreitmayer** [comment]
@species @almereyda you rock, thx!
