### ISSUE TITLE
translation of categories

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-editor#27]
The SUSY- or any other taxonomies in the editor should be translated 
- with the language of the browser 
- and/or with a language selector button.

**Comment by josefkreitmayer** [comment]
@species Südwind just emphasized, that this is a really important feature for them for the release on 6.3.

**Comment by species** [comment]
The SUSY taxonomy (types of initatives) are translated now and deployed on the TransforMap Editor. Will merge them into SUSY-Editor when users report no more errors.

**Comment by josefkreitmayer** [comment]
We got a reply, that there is a problem with WIN7 Firefox.

I also noticed that after checking again with my browser in an incognito window. The glitch is as follows:

When opening the window the first time ever, in the type of initiative-dropdown, the field is blank, and types do not show immeditaley, but just after clicking in the field. 

That might be confusing for the user, and is somewhat strange, as it does not happen with the communities-dropdown. Any ideas?

**Comment by species** [comment]
Hm cannot verify this win7+ff-problem - just checked.
It may be take a second (depending on Internet connection speed) to fill the TOI menu, but it should happen automatically without clicking somewhere.

The 'identity' field is currently generated hard-coded and does not need to load external resources, therefore it is there instantly.

**Comment by josefkreitmayer** [comment]
I tried it again right now. It just takes about a second to load, then all is there!
