### ISSUE TITLE
how to make links open in another tab in github

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-editor#30]
@almereyda @gandhiano are you probably familiar how to write a link in github help.md, so it opens in a new tab?

Want to put that with the links in the editor help.md: https://github.com/TransforMap/transformap-editor/blob/master/HELP.md

thx sincerely

**Comment by almereyda** [comment]
In Markdown, this is not possible. Additionally, opening links in the same
tab is default behaviour for HTML and has security inplications, as to
combat the use of new windows for so-called pop-unders.
The client logic presenting the file could take care of this, though, i.e.
by using a third-party MD display engine like jingo wiki or viewdocs.io,
which could be forked and changed respectively.

**Comment by josefkreitmayer** [comment]
Thx @almereyda for the swift reply. 
In the non-tech-user perspective, that simply means, not possible : )

Maybe at some point, when the editor is already quite solid, it would make sense to dedicate it it´s own HTML site for the helptext?
