### ISSUE TITLE
editor is not working with IE 

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-editor#32]
The editor is not working with IE
 - no map
- no drop dwon menu

**Comment by mrothauer** [comment]
are you referring to the new layout? if so, which version of IE? edge and IE11 are ok.

**Comment by josefkreitmayer** [comment]
@mrothauer, refering to the old beta before css, and with IE11.

**Comment by species** [comment]
Same thing as in the Viewer, fixable by adding this code https://github.com/TransforMap/transformap-viewer/commit/9b70115c7a7ea429deed6377318b5b1ef008c5ce .

I wonder where I should put this hacky bit of code, but wait until @mrothauer is finished with the styling.

**Comment by species** [comment]
Is now fixed and deployed on [transformap.co/transformap-editor/](http://transformap.co/transformap-editor/?place=e98fb9126657fd09e8c7e4321717ca17#2/47.0/15.5). Tested with IE11 on Win7.
