### ISSUE TITLE
bootstrap select - as enhancement for the dropdown

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-editor#33]
In the completion of the current CSS assignment, Mario mentioned, that Bootstrap Select could be a good enhancement of the Drop Down Menu. 

Here a link to the repo, which includes a small demo in the description: https://github.com/silviomoreto/bootstrap-select

Mario mentioned, that it would need a few more KB, and needs clarification with @species, if that would be welcome: 
Reqired are: 
-  jquery
- bootstrap dropdown js
- boostrap select js
- serveral CSS files

As Mario mentioned, that he cannot do it in the current assignment, but might contribute it at some point in the future, let´s hope for good fortune, and clarify the question, if a few more KB on the application would be welcome for this feature.

**Comment by species** [comment]
Thanks to @mrothauer and @almereyda, I was able to merge the changes into the deployed version of the TransforMap-editor as well as into the SUSY-Editor.

**Comment by josefkreitmayer** [comment]
@species,
I tried the transformap editor on smartphone. The bootstrap select featurw
is really sweet. It just takes very long to load any function after the
initial click on the dropdown (approx. 5 - 10 sec), so users might think it
is broken. Any ideas, how to improve?



Am 24.03.2017 20:02 schrieb "Michael Maier" <notifications@github.com>:
