### ISSUE TITLE
JS errors while starting application instance in development mode 

### ISSUE THREAD

**Issue by acorbi** [TransforMap/transformap-editor#41]
As a contributing developer I expect that, after following the instructions for development specified on the README.md file (installing dependencies and runing ```brunch watch --server -n```, the spawned application instance is error-free.

This is not the case currently on my machine, when I the application instance  i get:

![screenshot from 2017-07-14 16-52-33](https://user-images.githubusercontent.com/384894/28217283-e6835224-68b4-11e7-93b1-de905bfc884c.png)

tested on Firefox 54.0 (64-bit) on ubuntu linux

**Comment by almereyda** [comment]
If you could disable the concatenation of the used JS modules into `vendor.js`, we could identify the inherited upstream packages' modules involved in the errors. Then we may also find the pieces in our code, which invoke them.

**Comment by acorbi** [comment]
Identified problem which had to do with my local npm installation. After testing code in another machine and fixing & re-installing npm packages, development server starts properly now. Closing issue!
