### ISSUE TITLE
CSS - Stylesheet for editor

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-editor#9]
Including:

- Buttons
- Checkboxes for the Drop-Down menus
- Overall colour scheme, fonts, sizes, spacings
- how to design Readme (e.g. Link / Button to help page)

**Comment by almereyda** [comment]
From https://tree.taiga.io/project/transformap/us/408?no-milestone=1

> - colours
- shapes
- buttons

**Comment by josefkreitmayer** [comment]
closed in favour of representation at https://tree.taiga.io/project/transformap/us/408
